#!/bin/bash
NCores=22

CYAN=$(tput setaf 1)
RESET=$(tput sgr0)
rm -rf 0.orig
cp -r 0 0.orig
rm -rf 0/constant/polyMesh
rm -rf 0/constant/uniform
rm -rf constant/polyMesh

if [ ! -d Logs ]; then
    echo "Logs Created"
    mkdir Logs
fi

runPath=$(pwd)

echo "BlockMesh running in $runPath"
blockMesh > Logs/log.BlockMesh 2>&1

rm -rf processor*
echo "Decomposing for meshing in $runPath"
decomposePar > Logs/log.DecomposeParMeshing 2>&1

echo "Running snappyHexMesh in parallel in $runPath"
mpirun -np "$NCores" snappyHexMesh -overwrite -parallel > Logs/log.snappyHexMesh 2>&1

echo "Running reconstructParMesh in $runPath"
reconstructParMesh -constant > Logs/log.recontruct 2>&1
echo "Running toposet in $runPath"
topoSet>Logs.Toposet 2>&1
echo "Running refineMesh in $runPath"
#refineMesh -overwrite>Logs.refineMesh 2>&1
echo "Copying the 0.orig to 0 in $runPath"
cp -r 0.orig 0
echo "Removing the old alpha.water field"
rm -rf 0/alpha.water
cp -r 0/alpha.water.org 0/alpha.water
echo "Running setFields in $runPath"
setFields > Logs/log.setFields 2>&1

rm -rf processor*
#echo "Decomposing before solver in $runPath"
decomposePar > Logs/log.decomposePar 2>&1

#rm -rf postProcessing

echo "CheckMeshing before run in $runPath"
checkMesh > Logs/log.CheckMesh 2>&1
grep -r cells: Logs/log.CheckMesh | awk '{print $2}' > CellNumber

#echo "${CYAN}Running solver with $NCores cores in $runPath${RESET}"|tee Logs/RunTimeStatus 
#mpirun -np "$NCores" interFoam -parallel > Logs/log.solver 2>&1
#echo "Finished in $runPath" > Logs/RunTimeStatus 2>&1


#echo "$(tput setaf 3)Finished in $runPath$(tput sgr0)"
