#!/bin/bash

rm -r 0/alpha.water
cp -r 0/alpha.water.org 0/alpha.water


setFields|tee log.setFields
rm -r processor*
decomposePar
rm -r  postProcessing
#renumberMesh -overwrite
#decomposePar |tee log.decomposePar
mpirun -np 8 interFoam -parallel|tee log.solver
# reconstructParMesh -constant
# checkMesh
# #foamToVTK -faceSet polyMesh/sets/buscalaqueteinteresa -time 0
