// Null mjoint for the root-body
#include "mnullJoint.H"

// Composite mjoint to handle combination of rotations and translations
#include "mcompositeJoint.H"

// 6-DoF mjoint for mfloating mbodies
#include "floatingJoint.H"

// Revolute mjoints
#include "mRx.H"
#include "mRy.H"
#include "mRz.H"
#include "mRa.H"
#include "mRs.H"
#include "mRzyx.H"
#include "mRxyz.H"
#include "mRyxz.H"

// Prismatic mjoints
#include "mPx.H"
#include "mPy.H"
#include "mPz.H"
#include "mPa.H"
#include "mPxyz.H"
